(define (problem recife-c)
  (:domain recife-c)
  (:objects EsPR EsCAP EsPD EsAf EsMSJ EsSR
	IgrejaNSRP MercadoSJ PacoAlfandega BancoBrasil PracaRepublica
	Joao Maria Jose
	Bicicleta1 Bicicleta2 Bicicleta3 Bicicleta4 Bicicleta5 Bicicleta6 Bicicleta7 Bicicleta8
  )
  (:init
    (eh-estacao EsPR)
	(eh-estacao EsCAP)
	(eh-estacao EsPD)
	(eh-estacao EsAf)
	(eh-estacao EsMSJ)
	(eh-estacao EsSR)
    (eh-adjacente EsPR EsCAP) (eh-adjacente EsCAP EsPR) 
	(eh-adjacente EsPR EsPD) (eh-adjacente EsPD EsPR)
	(eh-adjacente EsCAP EsAf) (eh-adjacente EsAf EsCAP)
	(eh-adjacente EsAf EsSR) (eh-adjacente EsSR EsAf)
	(eh-adjacente EsSR EsPD) (eh-adjacente EsPD EsSR)
	(eh-adjacente EsSR EsMSJ) (eh-adjacente EsMSJ EsSR)
	(eh-adjacente EsMSJ EsPD) (eh-adjacente EsPD EsMSJ)
	(eh-ponto-visita IgrejaNSRP)
	(eh-ponto-visita MercadoSJ)
	(eh-ponto-visita PacoAlfandega)
	(eh-ponto-visita BancoBrasil)
	(eh-ponto-visita PracaRepublica)
	(eh-ponto-visita-prox IgrejaNSRP EsPD)
	(eh-ponto-visita-prox MercadoSJ EsMSJ)
	(eh-ponto-visita-prox PacoAlfandega EsAf)
	(eh-ponto-visita-prox BancoBrasil EsCAP)
	(eh-ponto-visita-prox PracaRepublica EsPR)
	(eh-ciclista Joao)
	(eh-ciclista Maria)
	(eh-ciclista Jose)
	(ciclista-em-estacao Joao EsPD)
	(ciclista-em-estacao Maria EsAf)
	(ciclista-em-estacao Jose EsCAP)
	(eh-bicicleta Bicicleta1)
	(eh-bicicleta Bicicleta2)
	(eh-bicicleta Bicicleta3)
	(eh-bicicleta Bicicleta4)
	(eh-bicicleta Bicicleta5)
	(eh-bicicleta Bicicleta6)
	(eh-bicicleta Bicicleta7)
	(eh-bicicleta Bicicleta8)
	(bicicleta-em-estacao Bicicleta1 EsPR)
	(bicicleta-em-estacao Bicicleta2 EsCAP)
	(bicicleta-em-estacao Bicicleta3 EsSR)
	(bicicleta-em-estacao Bicicleta4 EsSR)
	(bicicleta-em-estacao Bicicleta5 EsSR)
	(bicicleta-em-estacao Bicicleta6 EsMSJ)
	(bicicleta-em-estacao Bicicleta7 EsMSJ)
	(bicicleta-em-estacao Bicicleta8 EsPD)
	(not(ciclista-com-bicicleta Maria))
	(not(ciclista-com-bicicleta Joao))
	(not(ciclista-com-bicicleta Jose))
	(pode-pegar-bicicleta Maria)
	(pode-pegar-bicicleta Joao)
	(pode-pegar-bicicleta Jose)
  )
  (:goal (ciclista-em-estacao Joao EsCAP))
)
